### ISSUE TITLE
pypi has package with same name

### ISSUE THREAD

**Issue by AaronDavidSchneider** [exorad/gcmt#18]
Hi @robinbaeyens, @Kiefersv:
someone stole our idea (before we even had it) and published a package on pypi with the same name as our lovely package.
We should consider using a different name instead, in order to be able to publish on pypi.
Here is a suggestion: `gcm_utils`
Cheers
Aaron

**Comment by robinbaeyens** [comment]
That's too bad... I guess we'll need to think of a new name then indeed.
Some more suggestions `gcm_toolkit`, `py4gcm`.
Or we can try to think of a good-old acronym :)

**Comment by AaronDavidSchneider** [comment]
I vote for `gcmtoolkit`.

Please no acronym again :D :D :D

**Comment by Kiefersv** [comment]
I like `gcmtoolkit` as well! 
(But I disagree with Aaron, acronyms are amazing and should be as complicated as possible :D)

**Comment by AaronDavidSchneider** [comment]
Lets dub it gcmtoolkit then. I will do the change as soon as #17 is merged!

**Comment by AaronDavidSchneider** [comment]
> I think as soon as we fixed (and secured) a name we should think about a logo. If anyone of you wants to have a shot at it that would be great, otherwise I would ask some more artistically talented friends of mine :D

Sure, go ahaid :D I'd say its more important to do some broadcasting of our software... Get other people to use it and stuff, but sure a logo is nice as well :D :D

**Comment by Kiefersv** [comment]
Issue resolved, since we know changed the name to GCMT (short for GCMtoolkit) and reserved the pypi.org name.
