### ISSUE TITLE
Main data object (GCMDataset?)

### ISSUE THREAD

**Issue by robinbaeyens** [exorad/gcmt#3]
I briefly played around with having a `GCMDataset` object as subclass of `xarray.Dataset` to act as our main GCM data object. However, I decided against this because of two reasons:
- some behaviour that I didn't fully understand (e.g. attributes not being transferred)
- [this issue](https://xarray.pydata.org/en/stable/internals/extending-xarray.html), saying its not so straightforward to subclass xarray.Datasets

So I propose to just use straight-up xarray.Datasets and do consistent checks that our custom-defined methods do not violate the basic requirements that we set.

If somebody else wants have a go at having a Dataset subclass, go ahead!

**Comment by AaronDavidSchneider** [comment]
sounds like a good plan!
